services:
  gitea:
    image: gitea/gitea:1.25.5
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000

      - DB_TYPE=postgres
      - DB_HOST=gitea-db:5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWD=${POSTGRES_PASSWORD}
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    volumes:
      - gitea_data:/data
    ports:
      - 127.0.0.1:3000:3000
      - 127.0.0.1:22:22
    restart: always
    depends_on:
      gitea-db:
        condition: service_healthy
    networks:
      - internal-network
  gitea-db:
    image: postgres:13
    container_name: gitea-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - psql_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal-network

volumes:
  gitea_data:
  psql_data:
  
networks:
  internal-network:
    driver: bridge