---

# Update package 
- name: Update apt cache
  apt:
    update_cache: yes

# Install required packages for Docker
- name: Install required packages for Docker
  apt:
    name:
      - curl
      - git
    state: present

# Install Docker.io
- name: Install Docker.io
  apt:
    name: docker.io
    state: present

# Install Docker Compose plugin
- name: Install Docker Compose plugin
  apt:
    name: docker-compose-plugin
    state: present

# Ensure Docker service is running
- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes

