name: Security Scan

on: # Trigger the workflow on push or pull request to the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: # Set permissions for the workflow
  contents: read # Allow read access to the repository contents
  security-events: write # Allow write access to security events, needed for uploading SARIF reports
  actions: read # Allow read access to GitHub Actions, needed for running actions

jobs:
  security-scan:
    runs-on: ubuntu-24.04 # use the 24.04 Ubuntu 
    steps:

      - name : Checkout code # Checkout the repository to the Ubuntu runner
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
      


      - name: Gitleaks actions # Run Gitleaks to scan for secrets in the codebase
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use the GitHub token to authenticate with the repository



      - name: Trivy scan # Run Trivy to scan for vulnerabilities in the image
        uses: aquasecurity/trivy-action@master # Ensure you are using the latest version of the Trivy action
        with:
          image-ref: 'gitea/gitea:1.26.1' # Specify the image to scan
          format: 'sarif' # Output format for the scan results: SARIF format 
          severity: 'HIGH,CRITICAL' # Only report vulnerabilities with HIGH or CRITICAL severity
          ignore-unfixed: true # Ignore vulnerabilities that do not have a fix available
          exit-code: '1' # Set the exit code to 1 if vulns are found
          vuln-type: 'os,library' # Scan for both OS and library vulns
          output: 'trivy_report.sarif' # Specify the output file path for the scan results in SARIF format
          trivyignores: '.trivyignore' # Specify the path to the .trivyignore file to ignore certain vulnerabilities
        
      - name: Upload Trivy report to Github Security tab # Upload the Trivy scan results to Github Security tab
        uses: github/codeql-action/upload-sarif@v4
        if: always() # Ensure this step runs even if the previous step fails
        with:
          sarif_file: 'trivy_report.sarif' # Specify the SARIF file generated by Trivy


      - name: Checkov scan # Run Checkov to scan for vulnerabilities in the image
        uses: bridgecrewio/checkov-action@master # Ensure you are using the latest version of the Checkov action
        if: always() # Ensure this step runs even if the previous step fails
        with:
          output_format: cli,sarif # Output format for the scan results
          output_file_path: console,checkov_report.sarif # Specify the output file path for the scan results
      
      - name: Upload Checkov report to Github Security tab # Upload the Checkov scan results to Github Security tab
        uses: github/codeql-action/upload-sarif@v4
        if: always() # Ensure this step runs even if the previous step fails
        with:
          sarif_file: 'checkov_report.sarif' # Specify the SARIF file generated by Checkov